version: "7.0"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=server
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    init: true

  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - ./data/cache:/usr/local/etc/redis

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
      - cache
    environment:
      - TOKEN_SECRET=KuJcCQ0is27L/z926N9bzAdoKtkMBhkHxvR84wPBW8Q=
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/server?schema=public
      - PORT=3001
      - NODE_ENV=production
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:3001
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
