name: Deploy in Gihub Pages

on:
  schedule:
    - cron: "45 5 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          echo "This job is used to prepare the environment and metadata for the following jobs."
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          echo "This job is used to prepare the environment and metadata for the following jobs."
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - run: |
          yarn install
          yarn run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.x"
      - name: configure github pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - run: |
          yarn install
          yarn build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./.next"
      - name: deploy to github pages
        id: deploy
        uses: actions/deploy-pages@v1
